[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmd = "npm install --production --no-package-lock --ignore-scripts"

[phases.build]
cmd = "echo 'No build step needed'"

[start]
cmd = "node app.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_PACKAGE_LOCK = "false" 